### PR TITLE
Edge events config

### PR DESCRIPTION
**Pull request by brucearmstrong**
- Preference pages for Edge Events configuration.
- Defining summary providers, configuring for numeric input only, and handling hiding/showing of settings dependent on other settings is handled in matchingenginehelper/SettingsActivity.java
- Updating the EdgeEventsConfig is handled in onEdgeEventPreferenceChanged() in MatchingEngineHelper.java.
- _So_ many new strings! Thanks to @ah1053  for letting me borrow the values he came up with for Unity.
- Naming convention may seem odd for some of the string-array values. This is because I'm matching existing enum values, so I can use the enum.valueOf method instead of relying on string comparisons. This was a little tricky for FindCloudletEventTrigger, where you can arbitrarily select items from a list, but I like how straightforward it turned out. Search for `FindCloudletEventTrigger.valueOf` to admire some elegant code. :)
- Added coreLibraryDesugaring settings because before API 26, Android doesn't have the java.time package which is required by the com.android.volley HTTP library I'm using. See https://developer.android.com/studio/write/java8-support#library-desugaring. (Problem found thanks to @franklin-huang-mobiledgex's geriatric (4 year-old) phone.)

See https://mobiledgex.atlassian.net/wiki/spaces/SWDEV/pages/2178088972/Edge+Events+Preference+Screens+for+Android for screenshots and further explanations.

### CODE REVIEW

**Review by LeonAdams — COMMENTED** [review]
Looks good!

**Review by LeonAdams — APPROVED** [review]

**Review by franklin-huang-mobiledgex — APPROVED** [review]

**Review by lgarner — APPROVED** [review]
👍

**Review by franklin-huang-mobiledgex — APPROVED** [review]
thanks!

**Review by ah1053 — APPROVED** [review]
🥇

**Review by LeonAdams — APPROVED** [review]

**Pull request merged**
