### PR TITLE
Hiding API keys

### PR DESCRIPTION
**Pull request by brucearmstrong**
Also latest version for matchingengine.

### CODE REVIEW

**Comment by gainsley** [comment]
Are those keys something we really need to hide? Because they're still in the git history.

**Comment by lgarner** [comment]
Yes, because they really need to specify their own anyway (it’s attached to
a credit card, but you can see how a particular key is used).

**Comment by gainsley** [comment]
Sorry, what I meant to imply was we should generate new API keys for ourselves if we don't want people using the ones removed here, since they're still visible in the github history.

**Comment by brucearmstrong** [comment]
@gainsley: Google detected these keys when the repository was made public. I got an email from them suggesting remedies, including regenerating keys, which is what I did. 

My private versions of these files use the new keys, and I'm in the process of testing and publishing to Google Play, a new version of the app.

**Comment by gainsley** [comment]
@brucearmstrong awesome, thanks. That's pretty slick of google.

**Comment by brucearmstrong** [comment]
The keys viewable in the history will become invalid at Sep 19, 2019, 5:37:06 PM. I agree about Google's slickness. I was surprised, impressed, and embarrassed. :)

**Pull request merged**
